sudo: false
language: node_js
node_js:
  - '5.0'
  - '4.2'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-deployd' ]; then cd .. && eval "mv $currentfolder generator-deployd" && cd generator-deployd; fi
